example<-matrix(c(1,2,3,4,5,6,7,8),nrow=4, ncol=2)
source("https://bioconductor.org/biocLite.R")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.11")
BiocManager::available()
installed.packages("ggplot2") 
library(ggplot2)
browseVignettes("ggplot2")
colours()
library(devtools)
help(package="devtools")
library(KernSmooth)
